name: dojo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  # - notebook
  - jupyter_core==4.11.2
  - nbconvert==6.5.0
  - conda-forge::numpy==1.22.4 
  - pandas==1.4.2
  - scikit-learn==1.1.3
  - statsmodels==0.13.2
  - pip==22.3
  - nbconvert==6.5.0
  - conda-forge::shap==0.41.0
  - conda-forge::dython==0.7.1.post4
  # - jupyter
  - conda-forge::notebook==6.4.12
  # - conda-forge::jupyterlab
  - conda-forge::sktime==0.12.0
  - conda-forge::pandas-profiling==3.2.0
  - lightgbm==3.3.2 
  - python-graphviz==0.20
  - conda-forge::ipython==8.6.0
  - conda-forge::ipykernel==6.17.0

  - pip:
    - nbdime==3.1.1
    - beautifulsoup4==4.11.1
    # - bs4
    # - charset-normalizer==2.0.12
    - cycler==0.11.0
    - fonttools==4.29.1
    - geopy==2.2.0
    - idna==3.3
    - kaggle==1.5.12
    - interpret==0.2.7
    - ipywidgets==8.0.2
    - joblib==1.2.0
    - imbalanced-learn==0.9.1
    - kiwisolver==1.3.2
    - lime==0.2.0.1
    - lxml==4.9.0
    - matplotlib==3.4.3
    - missingno==0.5.1
    - nltk==3.7
    - openpyxl==3.0.10
    - tabulate==0.8.9
    - pmdarima==1.8.5
    - pandas-datareader==0.10.0
    - plotly==5.8.2
    - PyMySQL==1.0.2
    - pystan==2.19.1.1
    - prophet==1.0.1
    - SQLAlchemy==1.4.37 
    - sqlalchemy-utils==0.38.2
    - scipy==1.8.1
    - pillow==9.3.0
    - requests==2.28.1
    - seaborn==0.11.2
    - soupsieve==2.3.1
    - urllib3==1.26.8
    - tmdbsimple==2.9.1
    # - tensorflow
    - yelpapi==2.4.0
    - tensorflow==2.9.0
    - xgboost==1.6.1
    - yellowbrick==1.4
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-nbextensions-configurator==0.4.1
    

    
prefix: /Users/codingdojo/opt/anaconda3/envs/dojo-env
