name: dojo-env
channels:
  - conda-forge
  - defaults
  - apple
dependencies:
  - python=3.8.13
  - apple::tensorflow-deps==2.9.0
  # - notebook # testing adding back 06/22
  - nbconvert==6.5.0
  - conda-forge::numpy==1.22.4 
  - pandas==1.4.2
  - scikit-learn==1.1.3
  - statsmodels==0.13.2
  - pip==22.3
  - nbconvert==6.5.0
  - conda-forge::shap==0.41.0
  - conda-forge::dython==0.7.1.post4
  # - jupyter
  # - conda-forge::notebook==6.4.12
  - jupyter=1.0.0 #added 12/08/22
  # - conda-forge::jupyterlab
  # - conda-forge::jupyter_nbextensions_configurator==0.4.1
  # - prophet
  # - conda-forge::sktime==0.12.0 #-all-extras
  - conda-forge::pandas-profiling==3.2.0
  - lightgbm==3.3.2 
  - python-graphviz==0.20
  - conda-forge::ipython==8.6.0
  - conda-forge::ipykernel==6.17.0
  # - conda-forge::jupyter_core==4.11.2 # added 12/08/22

  # - conda-forge::pystan
  # - conda-forge::prophet
  - pip:
    - nbdime==3.1.1
    - beautifulsoup4==4.11.1
    - dataframe-image==0.1.3
    - html5lib==1.1
    # - charset-normalizer==2.0.12
    - tqdm==4.64.0
    - cycler==0.11.0
    - fonttools==4.29.1
    - geopy==2.2.0
    - idna==3.3
    - ipywidgets==8.0.2
    - interpret==0.2.7
    - joblib==1.2.0
    - imbalanced-learn==0.9.1
    - kaggle==1.5.12
    - kiwisolver==1.3.2
    - lime==0.2.0.1
    - lxml==4.9.0
    - matplotlib==3.4.3
    - missingno==0.5.1
    - nltk==3.7
    - openpyxl==3.0.10
    - tabulate==0.8.9
    - pmdarima==1.8.5
    - pandas-datareader==0.10.0
    - plotly==5.8.2
    # - pystan==2.19.1.1
    # - prophet==1.0.1
    - PyMySQL==1.0.2
    - SQLAlchemy==1.4.37 
    - sqlalchemy-utils==0.38.2
    - scipy==1.8.1
    # - sktime[all_extras]
    - pillow==9.3.0
    - requests==2.28.1
    - seaborn==0.11.2
    - soupsieve==2.3.1
    - urllib3==1.26.8
    - tmdbsimple==2.9.1
    - yelpapi==2.4.0
    - tensorflow-macos==2.9.2
    - tensorflow-metal==0.5.1
    - tensorflow_datasets
    - xgboost==1.6.1
    - yellowbrick==1.4
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-nbextensions-configurator==0.4.1

    
    
prefix: /Users/codingdojo/opt/anaconda3/envs/dojo-env
