name: dojo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.5
  - colour=0.1.5
  - contourpy=1.0.5
  - cryptography=38.0.1
  - cycler=0.11.0
  - cython=0.29.32
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - dataframe_image=0.1.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dython=0.7.2
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - fftw=3.3.9
  - flatbuffers=2.0.0
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - furl=2.1.2
  - gast=0.5.3
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.18
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - greenlet=2.0.1
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.7.0
  - hdf5=1.10.6
  - html5lib=1.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - imbalanced-learn=0.10.0
  - importlib-metadata=4.11.3
  - infinity=1.5
  - intel-openmp=2021.4.0
  - intervals=0.9.2
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.4.7
  - jupyter_console=6.4.3
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.3
  - jupyterlab_widgets=1.0.0
  - keras=2.9.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcurl=7.86.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxgboost=1.5.0
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - lightgbm=3.3.3
  - lime=0.2.0.1
  - llvmlite=0.39.1
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbdime=3.1.1
  - nbformat=5.7.0
  - nest-asyncio=1.5.5
  - networkx=2.8.4
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - oauthlib=3.2.1
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - orderedmultidict=1.0.1
  - packaging=21.3
  - pandas=1.5.2
  - pandas-datareader=0.10.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - passlib=1.7.4
  - patsy=0.5.2
  - pcre=8.45
  - pendulum=2.1.2
  - phonenumbers=8.12.27
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - ply=3.11
  - pmdarima=1.8.5
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.4
  - pure_eval=0.2.2
  - py-xgboost=1.5.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pymysql=1.0.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pytz=2022.1
  - pytzdata=2020.1
  - pywavelets=1.4.1
  - pywin32=305
  - pywinpty=2.0.2
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-image=0.19.3
  - scikit-learn=1.1.3
  - scikit-plot=0.3.7
  - scipy=1.9.3
  - seaborn=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - shap=0.41.0
  - sip=6.6.2
  - six=1.16.0
  - slicer=0.0.7
  - smmap=4.0.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.39
  - sqlalchemy-utils=0.38.3
  - sqlalchemy-utils-arrow=0.38.3
  - sqlalchemy-utils-babel=0.38.3
  - sqlalchemy-utils-base=0.38.3
  - sqlalchemy-utils-color=0.38.3
  - sqlalchemy-utils-encrypted=0.38.3
  - sqlalchemy-utils-intervals=0.38.3
  - sqlalchemy-utils-password=0.38.3
  - sqlalchemy-utils-pendulum=0.38.3
  - sqlalchemy-utils-phone=0.38.3
  - sqlalchemy-utils-timezone=0.38.3
  - sqlalchemy-utils-url=0.38.3
  - sqlite=3.40.0
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tabulate=0.9.0
  - tbb=2021.6.0
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - tensorflow-estimator=2.9.0
  - termcolor=2.1.0
  - terminado=0.13.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ucrt=10.0.20348.0
  - urllib3=1.26.13
  - vc=14.2
  - vs2015_runtime=14.32.31332
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.14.1
  - xgboost=1.5.0
  - xlsxwriter=3.0.3
  - xz=5.2.8
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - jupyter-contrib-core==0.4.2
    - jupyter-contrib-nbextensions==0.7.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-nbextensions-configurator==0.6.1
    - plotly==5.11.0
    - pytz-deprecation-shim==0.1.0.post0
    - tenacity==8.1.0
    - tzdata==2022.7
    - tzlocal==4.2
prefix: C:\Users\james\Anaconda3\envs\dojo-env
